configured_endpoints: 60
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/signify-holdings%2Frain-hello-world-b1d0edde62045b9581d493c63fb16e36fca49ebadcbdf07242ee974852e44f94.yml
openapi_spec_hash: 2b08f3b547c856bd69c4d1720b9a58fd
config_hash: fcbe9d3d1ea30c5b42c389acb3fd0faf
