configured_endpoints: 60
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/signify-holdings%2Frain-hello-world-c84cf0c7eff3cf8e103faeaa92f6bdf6d16abf5805dc0d5cbdb6ca2df036365d.yml
openapi_spec_hash: dc073e4aab6c6c32f53a9022e532b00f
config_hash: 20b0245c8fd117caa01fa6f9887a837b
